# Generated by Django 3.0.4 on 2021-01-22 23:14

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título:')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa:')),
                ('description', froala_editor.fields.FroalaField(verbose_name='Descricao:')),
                ('image', models.ImageField(max_length=255, upload_to='experiences/images', verbose_name='Imagem da empresa:')),
                ('status', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['-id'],
            },
        ),
    ]
