# Generated by Django 3.0.4 on 2021-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20210122_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(verbose_name='Saída em:'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(verbose_name='Entrada em:'),
        ),
    ]
