# Generated by Django 3.0.4 on 2021-01-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_auto_20210123_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='Saída em:'),
        ),
    ]
