# Generated by Django 3.0.4 on 2021-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Título:')),
                ('rating', models.CharField(choices=[('1', 'Básico'), ('2', 'Iniciante'), ('3', 'Bom'), ('4', 'Intermediário'), ('5', 'Avançado')], max_length=200)),
                ('image', models.ImageField(max_length=255, upload_to='skills/images', verbose_name='Imagem da habilidade:')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['-id'],
            },
        ),
    ]
