# Generated by Django 3.0.4 on 2021-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rating',
            field=models.CharField(choices=[('1', 'Básico'), ('2', 'Iniciante'), ('3', 'Bom'), ('4', 'Intermediário'), ('5', 'Avançado')], max_length=200, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
