# Generated by Django 3.0.4 on 2021-01-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFormations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome:')),
                ('institution', models.CharField(max_length=100, verbose_name='Instituição:')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(max_length=255, upload_to='academic_formations/images', verbose_name='Imagem da instituição:')),
                ('status', models.BooleanField(default=True, verbose_name='Status:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formação acadêmica',
                'verbose_name_plural': 'Formações acadêmica',
                'ordering': ['-id'],
            },
        ),
    ]
