# Generated by Django 3.0.4 on 2021-01-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210121_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
